export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';
export const LOGOUT_IS_LOADING = 'LOGOUT_IS_LOADING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';